apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-s4gv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qete-tenant/rhtap-demo-app/hacbs-test-project-s4gv@sha256:b6cf8c76e905c0efdfa4e4af5042d4bd5e2191600f80fe907f7cea132acfdd83
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
