apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-s4gv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-s4gv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-s4gv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-s4gv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-s4gv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qete-tenant/rhtap-demo-app/hacbs-test-project-s4gv@sha256:b6cf8c76e905c0efdfa4e4af5042d4bd5e2191600f80fe907f7cea132acfdd83
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
